### ISSUE TITLE
API calls - Android Project

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#116]
In latest commit, isTest introduced. When this is true, API returns predefined static successful responses so that implementation of UI can move on. So previously implemented calls and new calls has to be implemented with this approach.
Also API calls that are under development should return predefined responses no matter isTest value set to. So hierarchy for responses is:

If **underDevelopment** then return **predefined response**
elsif **isTest** then return **predefined response**
else **make the call and return the response**
endif

Comment, Rating and new search call has to be implemented. Also predefined responses has to be created.

**Comment by onurguler** [comment]
Well done, we will take this from here...
