### ISSUE TITLE
Profile Page, Restaurant mode - Android Project

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#117]
When new field on User model **isRestaurant** is true, profile page list has to be show related menu items for current user(recyclerview has to be updated to show menu items and also recipe items. So new type of row has to be created and recycler view adapter has to be updated to show both of them).

Also `add` function has to be updated to lead user to menu creation or recipe creation page. These user can create recipes also menus.

**Comment by akintoksan** [comment]
Menu dropdown list has been implemented: 41b27915efbad77a0df680eb939b481213869d9b

**Comment by kerata** [comment]
These features added few commits ago...
