### ISSUE TITLE
Null response on comment recipe call - BackEnd

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#141]
Even when there are no comments exists, there should be an answer such as {} or [] ...

http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/comment/recipe/3

No Response...

**Comment by grkmndr** [comment]
The bug is fixed, the response is [] now. Do we need the same functionality for the ratings as well or is it okay to return null for them ?
