### ISSUE TITLE
Rating Strategy - BackEnd

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#145]
When average is calculated, rate request coming from same user(userId) should be overwritten with the old value if there are any. Currently it seems every rate request considered as new. In the example below, user rates 3 stars but then changes to 2, first average comes as 3(presumed he was the first) but then average comes as 2.5((2 + 3)/2). If this is the case, it is a wrong approach.

I am appending logcat dump below.

12-18 20:44:39.650 26333-26333/com.boun.swe.wawwe V/Request: http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/rate, method: POST
12-18 20:44:39.650 26333-26333/com.boun.swe.wawwe V/Request: {"parentId":2,"rating":3.0,"type":"recipe"}
12-18 20:44:40.269 26333-26348/com.boun.swe.wawwe V/Response: {"id":15,"userId":8,"type":"recipe","parentId":2,"rating":3.0,"createdAt":null}
12-18 20:44:40.274 26333-26333/com.boun.swe.wawwe V/Request: http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/rate/recipe/2, method: GET
12-18 20:44:40.519 26333-26351/com.boun.swe.wawwe V/Response: 3.0
12-18 20:45:04.403 26333-26333/com.boun.swe.wawwe V/Request: http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/rate, method: POST
12-18 20:45:04.403 26333-26333/com.boun.swe.wawwe V/Request: {"parentId":2,"rating":2.0,"type":"recipe"}
12-18 20:45:04.723 26333-26350/com.boun.swe.wawwe V/Response: {"id":16,"userId":8,"type":"recipe","parentId":2,"rating":2.0,"createdAt":null}
12-18 20:45:04.728 26333-26333/com.boun.swe.wawwe V/Request: http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/rate/recipe/2, method: GET
12-18 20:45:05.028 26333-26349/com.boun.swe.wawwe V/Response: 2.5

**Comment by grkmndr** [comment]
The problem is fixed.
