### ISSUE TITLE
Recipe and Menu Apis

### ISSUE THREAD

**Issue by onurguler** [bounswe/bounswe2015group1#146]
After creating recipe, response is: (Recipe is created)
{"id":15,"userId":6,"name":"Deneme","ingredients":[{"ingredientId":"PlaceHolder","name":"tomato","amount":10,"unit":"kg"}],"description":"Deneme how to","tags":null,"createdAt":null,"nutritions":null}

But I cannot get the recipe with get request to
http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/recipe/view/15

The same thing is also for the menus.
After creating menu, response is: (Menu is created)
{"id":17,"name":"Deneme Menu","userId":7,"recipeIds":[],"createdAt":null,"period":"monthly","recipeNames":null,"description":"Menu Desc"}
But I cannot get the menu with get request to
http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/menu/17

**Comment by onurmus** [comment]
Can you send the Json that you send with api?

**Comment by onurmus** [comment]
This JSON format is old, please use new format. You can find new format under https://github.com/bounswe/bounswe2015group1/wiki/RestApiDocsJSONS

**Comment by kerata** [comment]
This issue is outdated and latest tests do not contain this issue...
