### ISSUE TITLE
Null createdAt response on makeComment Call - BackEnd

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#150]
This issue causes crash on client side...

Request:
http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/comment, method: POST
{"body":"Saat nerdeyse 4 bu mal 20:56 yaziyo:s","parentId":7,"type":"recipe"}

Response:
{"id":7,"userId":6,"type":"recipe","parentId":7,"body":"Saat nerdeyse 4 bu mal 20:56 yaziyo:s","userFullName":"Mert Tiftikci","createdAt":null}

**Comment by grkmndr** [comment]
Previously we were returning the createdAt field null for addRecipe, addComment, addMenu functions. I fixed the addComment and the addMenu part. Onur should fix the addRecipe part now.

**Comment by caglabalcik** [comment]
bugs are fixed
