### ISSUE TITLE
Comment createdAt field - BackEnd

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#151]
It seems createdAt values comes as day, it does not consider what time is it at the moment...

Request: (Request time for makeComment calls are about 03:40 - 04:00)
http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/comment/recipe/7

Response: [{"id":5,"userId":6,"type":"recipe","parentId":7,"body":"Boyle tarif mi olur lan:/!!","userFullName":"Mert Tiftikci","createdAt":1450569600000},{"id":6,"userId":6,"type":"recipe","parentId":7,"body":"Saati yanlis aldim galiba:s","userFullName":"Mert Tiftikci","createdAt":1450569600000},{"id":7,"userId":6,"type":"recipe","parentId":7,"body":"Saat nerdeyse 4 bu mal 20:56 yaziyo:s","userFullName":"Mert Tiftikci","createdAt":1450569600000}]

1450569600000 => Sun Dec 20 02:00:00 2015 GMT+2:00

**Comment by grkmndr** [comment]
Fixed
