### ISSUE TITLE
userUpdate call return problem - BackEnd

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#152]
id and dateOfBirth fields comes empty on response...

Request:
http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/user/update, method: POST
{"email":"merttiftikci@gmail.com","fullName":"Mert Tiftikci","isRestaurant":true,"location":"istanbul","password":"mama"}

Response: {"id":-1,"email":"merttiftikci@gmail.com","fullName":"Mert Tiftikci","location":"istanbul","dateOfBirth":null,"isRestaurant":true,"rating":null}

**Comment by grkmndr** [comment]
The id field should be included in the post body because we need to check if the current user is updating himself/herself.

**Comment by kerata** [comment]
This bug is fixed
