### ISSUE TITLE
getAllMenus and getAllRecipes rate - BackEnd

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#153]
Menu models returns rate values now, but they are null and Recipe models do not return rate field at all.

Request: http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/recipe/all, method: GET
Request: http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/menu, method: GET
Response: [{"id":2,"userId":2,"name":"mercimek Ã§orba","ingredients":[{"ingredientId":"4asdas","name":"mercimek","amount":3},{"ingredientId":"9ada","name":"salÃ§a","amount":4}],"description":"benim Ã§orbam","tags":["sÄ±hhat","iÃ§","bul","merci"],"createdAt":1450577455841,"nutritions":{"id":1,"calories":6.2,"carbohydrate":2.2,"fats":8.0,"proteins":5.1,"sodium":9.5,"fiber":1.1,"cholesterol":3.2,"sugars":0.0,"iron":2.0}},{"id":3,"userId":2,"name":"omelette","ingredients":[{"ingredientId":"4asdxas","name":"egg","amount":3},{"ingredientId":"9adxa","name":"cheese","amount":5}],"description":"my omelette","tags":["breakfast","egg","omelette","cheese"],"createdAt":1450577455842,"nutritions":{"id":2,"calories":6.5,"carbohydrate":4.2,"fats":8.0,"proteins":5.1,"sodium":9.5,"fiber":1.1,"cholesterol":3.2,"sugars":0.0,"iron":2.0}},{"id":4,"userId":2,"name":"omelette","ingredients":[{"ingredientId":"4asdxas","name":"egg","amount":3},{"ingredientId":"9adxa","name":"cheese","amount":5}],"description":"my omelette","tags":["cheese","egg","omelette","breakfast"],"createdAt":1450577455842,"nutritions":{"id":3,"calories":6.5,"carbohydrate":4.2,"fats":8.0,"proteins":5.1,"sodium":9.5,"fiber":1.1,"cholesterol":3.2,"sugars":0.0,"iron":2.0}},{"id":5,"userId":2,"name":"omelette","ingredients":[{"ingredientId":"9adxa","name":"cheese","amount":5}],"description":"my omelette","tags":["egg","omelette","cheese","breakfast"],"createdAt":1450577455842,"nutritions":{"id":4,"calories":6.5,"carbohydrate":4.2,"fats":8.0,"proteins":5.1,"sodium":9.5,"fiber":1.1,"cholesterol":3.2,"sugars":0.0,"iron":2.0}},{"id":7,"userId":5,"name":"Test","ingredients":[{"ingredientId":"55603405f6b163b31e92b2ec","name":"Eggs, Large","amount":3}],"description":"Filan","tags":["Falan"],"createdAt":1450483200000,"nutritions":{"id":5,"calories":210.0,"carbohydrate":0.0,"fats":0.0,"proteins":18.0,"sodium":210.0,"fiber":0.0,"cholesterol":0.0,"sugars":0.0,"iron":0.0}}]
Response: [{"id":5,"name":"menum","userId":2,"recipeIds":[1],"createdAt":1449964800000,"period":"weekly","recipeNames":["Ã§iÄkÃ¶fte"],"description":null,"rating":null},{"id":6,"name":"menum","userId":2,"recipeIds":[1],"createdAt":1449964800000,"period":"weekly","recipeNames":["Ã§iÄkÃ¶fte"],"description":null,"rating":null},{"id":7,"name":"menum","userId":2,"recipeIds":[1],"createdAt":1449964800000,"period":"weekly","recipeNames":["Ã§iÄkÃ¶fte"],"description":"bu benim menum","rating":null},{"id":8,"name":"menum","userId":2,"recipeIds":[1],"createdAt":1449964800000,"period":"weekly","recipeNames":["Ã§iÄkÃ¶fte"],"description":"bu benim menum","rating":null},{"id":9,"name":"menÃ¼m","userId":2,"recipeIds":[1],"createdAt":1449964800000,"period":"weekly","recipeNames":["Ã§iÄkÃ¶fte"],"description":"bu benim menum","rating":null},{"id":10,"name":"menum","userId":2,"recipeIds":[2,3],"createdAt":1449964800000,"period":"weekly","recipeNames":["mercimek Ã§orba","omelette"],"description":"HARIKA","rating":null}]

**Comment by grkmndr** [comment]
All get methods for menus now return a rating value. (They return 0 if there's no rating for them yet.)

**Comment by onurmus** [comment]
Rating field for Recipe added. you should look RestApiDoc for new Recipe Object
