### ISSUE TITLE
User cannot logout if some of the fields are left empty in the sign up process - Android

### ISSUE THREAD

**Issue by akintoksan** [bounswe/bounswe2015group1#154]

**Comment by akintoksan** [comment]
In the Signup fragment, if you remove fullNameEditText, locationEditText, dateOfBirthEditText below, we can create a new user even if we left those fields empty. But, when you logged in, you cannot logout with this user. fullname and location is returned as "" (empty string) instead of null while adding the user to the database (unlike the web frontend).  I think this might be the problem.

if (!isInputValid(new EditText[]{
                        emailEditText, passwordEditText, fullNameEditText, locationEditText, dateOfBirthEditText})) {
                    return;
                }

**Comment by kerata** [comment]
This caused because authorization did not called after user creation, required call added and tested.
