### ISSUE TITLE
DatePicker in the Signup page always gets the month as January after the date selection

### ISSUE THREAD

**Issue by akintoksan** [bounswe/bounswe2015group1#155]

**Comment by kerata** [comment]
This could not be observed in tests...

**Comment by akintoksan** [comment]
Problem has not been solved

**Comment by akintoksan** [comment]
I think the problem is with the method prettifyDate(Date date) in the Commons class. Datepicker takes the day, month and year variables correctly. I'm working on it to fix :)

**Comment by akintoksan** [comment]
It turns out that there is something wrong with the "Date dateBirth" variable, it shows the month wrong as a String, but I fixed the problem both for Signup and Profile Edit pages :)
