### ISSUE TITLE
Trouble in registering

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group1#157]
I wanted to register to Mama (http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/)

I wanted to register and entered information in various ways, however, I can not click on register button. The cursor appears to be in a disabled state. I have no idea if any of the fields are not satisfying criteria or what. 

I expected to be able to create a new account named user: uskudarli. Alas, I am stuck on this page.

I am attaching the screenshot, showing the data.
![bug_group1_mama_registrationproblem](https://cloud.githubusercontent.com/assets/1347035/12010559/1bdf9fae-acb4-11e5-960a-520e4b60e5ec.png)

**Comment by AlperYayikci01** [comment]
I had fixed that bug, but Web frontend was not deployed to server. It is deployed now and i verified it works. Closing this issue.
