### ISSUE TITLE
Problem With Recipe Update - Backend

### ISSUE THREAD

**Issue by sleepnir** [bounswe/bounswe2015group1#173]
After I tried to update my recipe and sent required call for it, although it returned 200, the recipe is not updated. JSON string that I have sent is:

{"id":16,"name":"Açık Ayran","ingredients":[{"ingredientId":"558d968ea6a18cec1189871c","name":"Turkish Style Ayran Yogurt Drink","amount":5}],"description":"Would you like to have some açık ayran? Updated","tags":["ayran","open"],"nutritions":{"calories":630,"carbohydrate":20,"fats":50,"proteins":30,"sodium":3000,"fiber":0,"cholesterol":185,"sugars":20,"iron":0}}

**Comment by caglabalcik** [comment]
no problem :+1:

**Comment by sleepnir** [comment]
Ok, but any feedback about what I am doing wrong or why it is returning 200 and not updating?

**Comment by grkmndr** [comment]
Okay I will look into this problem.

**Comment by onurmus** [comment]
problem is you do not send "userId" parameter in JSON. we control that whether the recipe that wanted to be updated is belong to the user that have session. So you should send current Session's userId as userId parameter. Please try again
