### ISSUE TITLE
Create Activity Diagram

### ISSUE THREAD

**Issue by sleepnir** [bounswe/bounswe2015group1#37]
Create an activity diagram using several use cases.

Use cases to be used in creation: Add recipe, Basic Search, Advanced Search.

@kuzux @onurguler @grkmndr @onurmus @pinarsigin @HarunAcarbu @alphekimoglu @AlperYayikci01 @caglabalcik @kerata

**Comment by caglabalcik** [comment]
activity diagram revised

**Comment by pinarsigin** [comment]
An update on activity diagram : home page --> login page
