### ISSUE TITLE
finding unique name for the project

### ISSUE THREAD

**Issue by caglabalcik** [bounswe/bounswe2015group1#39]
discussion goes here!
@kuzux @AlperYayikci01 @alphekimoglu @cantunca @kerata @grkmndr @onurguler @onurmus @pinarsigin @sleepnir

**Comment by caglabalcik** [comment]
my suggestion: Mama

**Comment by sleepnir** [comment]
My suggestion is "Real Digest"

**Comment by pinarsigin** [comment]
Connectifood is my suggestion :)

**Comment by alphekimoglu** [comment]
My suggestion is "Yiyin Gayri"

**Comment by AlperYayikci01** [comment]
I vote for "Connectifood" also

**Comment by kuzux** [comment]
mama guzelmis lan

**Comment by caglabalcik** [comment]
we decided it to be MAMA
