### ISSUE TITLE
Revising requirements for semantic tagging, search and recommendation system

### ISSUE THREAD

**Issue by onurmus** [bounswe/bounswe2015group1#65]
According to the talk that was done 13.10.215 in class with assistant , revise requirements for semantic tagging, search and recommendation system

**Comment by caglabalcik** [comment]
Requirements are revised and some changes are made.

**Comment by caglabalcik** [comment]
1.1.8 Semantic Tagging
1.1.8.1 The results of the advanced search shall include recipes, ingredients and restaurants that are semantically related to the search query via semantic tagging.

1.1.9 Recommendations
1.1.9.1 Users shall be recommended food according to their most frequently searched food and nutrition preferences on their profiles.

Revisements shall be checked and re-revised for finalising.

**Comment by caglabalcik** [comment]
@onurmus

**Comment by onurmus** [comment]
I revise your work and also the part of non functional requirements. Good job girl!

**Comment by caglabalcik** [comment]
Thanks man!
