### ISSUE TITLE
Recipe Creation Fragment

### ISSUE THREAD

**Issue by kerata** [bounswe/bounswe2015group1#73]

**Comment by akintoksan** [comment]
@kuzux @onurmus @onurguler waiting for recipe creation API call.

Current setup for models, waitin for POST() and GET() for these classes: 
- Ingredient
     String name;
     float amount;
     int amountType; ("--", "gram", "kilogram", "teaspoon", "tablespoon", "cups")

- Recipe 
     String name;
     String directions;
     List<Ingredient> ingredients;
