### ISSUE TITLE
User update not working (android)

### ISSUE THREAD

**Issue by onurguler** [bounswe/bounswe2015group1#94]
Updated user infos are not preserved for the future sessions.
Also an error when the user tries to update their info if they did not click rememberme checkbox when logged in.

**Comment by onurguler** [comment]
Error is fixed but there is still a problem about updating the user info in the server. @kuzux

**Comment by kerata** [comment]
Request: http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/user/update (POST)
Body: {"dateOfBirth":"1993-06-21","email":"merttiftikci@gmail.com","fullName":"Mert Tiftikci","location":"Istanbul","password":"mama"}

Response: {"id":-1,"email":"merttiftikci@gmail.com","fullName":"Mert Tiftikci","location":"Istanbul","dateOfBirth":740620800000}

After this operation:
Request: http://ec2-52-89-168-70.us-west-2.compute.amazonaws.com:8080/api/user/1 (GET)
Response: {"id": 1,"email": "merttiftikci@gmail.com","fullName": null,"location": null,"dateOfBirth": null}

It does not seem to be updating, only converting date to time stamp.

Also, should we send date value in unix time stamp format or yyyy-MM-dd format?

**Comment by kerata** [comment]
User update now working... Appears there is a control for userId in update call which requires caller to send userId to double check.
